# Generated by Django 3.2.5 on 2021-07-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='img',
            field=models.ImageField(default=0, upload_to='imagess'),
            preserve_default=False,
        ),
    ]
